project(lyrics-on-panel-plasma6)
cmake_minimum_required(VERSION 4.0)
find_package(ECM REQUIRED NO_MODULE)
find_package(Qt6 REQUIRED COMPONENTS DBus)
set(CMAKE_MODULE_PATH ${ECM_MODULE_PATH} ${CMAKE_MODULE_PATH})
find_package(Plasma REQUIRED)
include(ECMFindQmlModule)
include(ECMQmlModule)
include(CheckIncludeFiles)
include(KDECMakeSettings)
include(KDEInstallDirs)
include(GenerateExportHeader)
add_subdirectory(dbus)
plasma_install_package(package lyrics-on-panel-plasma6)
